/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.CtrlCliente;
import Modelo.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JEFERSSON
 */
public class ClienteGui extends javax.swing.JInternalFrame {

    CtrlCliente objCtrlCli=new CtrlCliente();
    DefaultTableModel modelo;//modelo de datos
    TableRowSorter<TableModel> elqueOrdena;
    public static String ACCION;
    public static int codigoCliente;
    
    
    public ClienteGui() {
        initComponents();
        btnEditarCliente.setEnabled(false);
//        btnEliminarCliente.setEnabled(false);
        EsconderColumnaCodigo();
        llenarJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnNuevoCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gestion Cliente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar:");

        txtBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyReleased(evt);
            }
        });

        tblClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigoCliente", "Nombre", "Apellido", "Tipo de Identidad", "Nro Documento", "Fecha Nacimiento", "Genero", "Direccion", "Telefono", "Email", "Ciudad", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setRowHeight(22);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        btnNuevoCliente.setBackground(new java.awt.Color(9, 46, 227));
        btnNuevoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnEditarCliente.setBackground(new java.awt.Color(241, 100, 14));
        btnEditarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setText("Editar");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, Short.MAX_VALUE)
                        .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnNuevoCliente)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyReleased
        String buscarC;
        buscarC=txtBuscarCliente.getText();
        buscarEnTiempoReal(buscarC);
    }//GEN-LAST:event_txtBuscarClienteKeyReleased

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
       ACCION="Nuevo";
       FormClienteGui objForCliGui=new FormClienteGui(null, true);
       objForCliGui.setVisible(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        ACCION="Editar";
        System.out.println(codigoCliente);
        int filasele=0;
            filasele=tblClientes.getSelectedRow();
            System.out.println("filasele="+filasele);
            codigoCliente=Integer.valueOf(tblClientes.getValueAt(filasele, 0).toString());
            System.out.println("codigocliente= "+codigoCliente);
        FormClienteGui objFormClieGui=new FormClienteGui(null, true);
        objFormClieGui.setVisible(true);
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
            btnEditarCliente.setEnabled(true);            
            JOptionPane.showMessageDialog(null,"Entre evenclick table");
            
//            btnEliminarCliente.setEnabled(true);            
    }//GEN-LAST:event_tblClientesMouseClicked
    
    public void buscarEnTiempoReal(String texto){
        borrarJtable();//borro lo que hay en el JTABLE
        modelo=(DefaultTableModel)tblClientes.getModel();
        elqueOrdena=new TableRowSorter<TableModel>(modelo);
        tblClientes.setRowSorter(elqueOrdena);//con esto se puede ordenar por col el jtable de manera asc o desc
        CtrlCliente objctrlC=new CtrlCliente();
                
        ArrayList<Cliente> listado=new ArrayList();
        listado=objctrlC.BusquedaTiempoRealDos(texto);
        
        Object []col=new Object[modelo.getColumnCount()];//creo un obj tipo Object del tamaño de las columnas de mi Table
        for(int index=0;index<listado.size();index++){//recorro el arrayList
            col[0]=listado.get(index).getCodigoCliente();
            col[1]=listado.get(index).getNombre();
            col[2]=listado.get(index).getApellido();
            col[3]=listado.get(index).getNombreTipoIdentidad();
            col[4]=listado.get(index).getNumeroDocumento();
            col[5]=listado.get(index).getFechaNacimiento();
            col[6]=listado.get(index).getGenero();
            col[7]=listado.get(index).getDireccion();            
            col[8]=listado.get(index).getTelefono();
            col[9]=listado.get(index).getEmail();
            col[10]=listado.get(index).getNombreCiu(); 
            col[11]=listado.get(index).getEstado();
             modelo.addRow(col);//añado el object a la fila
        } 
       
      tblClientes.setModel(modelo);
         
     }
     
    private void borrarJtable(){
        for (int i = tblClientes.getRowCount() -1; i >= 0; i--){ 
                modelo.removeRow(i); 
        }      
    }
    
    /**
     * @param args the command line arguments
     */
    
    public void llenarJTable(){
        
        modelo=(DefaultTableModel)tblClientes.getModel();                
        elqueOrdena=new TableRowSorter<TableModel>(modelo);
        tblClientes.setRowSorter(elqueOrdena);//con esto se puede ordenar por col el jtable de manera asc o desc
        Cliente objC=new Cliente();
        ArrayList<Cliente> listado=new ArrayList<Cliente>();
        listado=objCtrlCli.traerTodosDos();
        Object []col=new Object[modelo.getColumnCount()];//creo un obj tipo Object del tamaño de las columnas de mi Table
        
        for(int index=0;index<listado.size();index++){
            col[0]=listado.get(index).getCodigoCliente();
            col[1]=listado.get(index).getNombre();
            col[2]=listado.get(index).getApellido();
            col[3]=listado.get(index).getNombreTipoIdentidad();
            col[4]=listado.get(index).getNumeroDocumento();
            col[5]=listado.get(index).getFechaNacimiento();
            col[6]=listado.get(index).getGenero();
            col[7]=listado.get(index).getDireccion();            
            col[8]=listado.get(index).getTelefono();
            col[9]=listado.get(index).getEmail();            
            col[10]=listado.get(index).getNombreCiu();
            col[11]=listado.get(index).getEstado();
            
            modelo.addRow(col);
        }
           
    }
    
    
     public void EsconderColumnaCodigo(){
        //metodo para esconder la columna que contiene el codigo de los contactos
        tblClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblClientes.getColumnModel().getColumn(0).setMinWidth(0);
        tblClientes.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblClientes.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ClienteGui dialog = new ClienteGui(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscarCliente;
    // End of variables declaration//GEN-END:variables
}
