/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.CtrlCiudad;
import Control.CtrlCliente;
import Control.CtrlTipoIdentidad;
import Modelo.Ciudad;
import Modelo.Cliente;
import Modelo.TipoIdentidad;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JEFERSSON
 */
public class FormClienteGui extends javax.swing.JDialog {

     
    CtrlCliente objCtrlCli=new CtrlCliente();
    CtrlTipoIdentidad objCtrlTI=new CtrlTipoIdentidad();
    CtrlCiudad objCtrlCiu=new CtrlCiudad();
    
    DefaultTableModel modelo;//modelo de datos
    TableRowSorter<TableModel> elqueOrdena;
    
    String accionFormCliGui="";
            
    public FormClienteGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        jDateSFechaNac.setDateFormatString("yyyy-MM-dd");//dar formato a la fecha, por defecto viene dd/MM/yyyy
        ((JTextField) this.jDateSFechaNac.getDateEditor()).setEditable(false);//para no editar en el jDateShooser
        txtIdTipoIden.setVisible(false);
        txtCodiCiudad.setVisible(false);
        setLocationRelativeTo(null);
        objCtrlTI.cargarCB(cbxTipoIdent);
        objCtrlCiu.cargarCB(cbxCiudad);        
        accionFormCliGui=ClienteGui.ACCION;
        
        if(accionFormCliGui.compareTo("Editar")==0){
            buscar(ClienteGui.codigoCliente);
            btnGuardar.setText("Editar");
        }else if(accionFormCliGui.compareTo("Nuevo")==0){
            btnGuardar.setText("Guardar");
        }              
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateSFechaNac = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cbxTipoIdent = new javax.swing.JComboBox();
        txtNroDocu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox();
        cbxCiudad = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIdTipoIden = new javax.swing.JTextField();
        txtCodiCiudad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO CLIENTE");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Fecha Nacimiento:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nro documento:");

        cbxTipoIdent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxTipoIdent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoIdentActionPerformed(evt);
            }
        });

        txtNroDocu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroDocuKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tipo Identidad:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Genero:");

        cbxGenero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        cbxCiudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCiudadActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ciudad:");

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Direccion:");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Telefono:");

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Email:");

        txtIdTipoIden.setEditable(false);

        txtCodiCiudad.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Estado:");

        cbxEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEmail)
                        .addComponent(txtApellido)
                        .addComponent(txtNombre)
                        .addComponent(txtDireccion)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateSFechaNac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(txtNroDocu, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxTipoIdent, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtIdTipoIden, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodiCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtTelefono))
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateSFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxTipoIdent, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdTipoIden))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNroDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodiCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(25, 115, 14));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(224, 79, 37));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void buscar(int codigoCliente){
        ArrayList<Cliente> cliente=new ArrayList();
        cliente=objCtrlCli.traerUnCliente(codigoCliente);
        int tam=cliente.size();
        
        for(int index=0;index<tam;index++){
            txtNombre.setText(cliente.get(index).getNombre());
            txtApellido.setText(cliente.get(index).getApellido());
            jDateSFechaNac.setDate(cliente.get(index).getFechaNacimiento());            
            posicioneCBTipoIden(cliente.get(index).getNombreTipoIdentidad());
            txtNroDocu.setText(cliente.get(index).getNumeroDocumento());
            posicioneCBGenero(cliente.get(index).getGenero());            
            posicioneCBCiudad(cliente.get(index).getNombreCiu());
            txtDireccion.setText(cliente.get(index).getDireccion());
            txtTelefono.setText(cliente.get(index).getTelefono());
            txtEmail.setText(cliente.get(index).getEmail());
            posicioneCBEstado(cliente.get(index).getEstado());
        }
    }
    
    public void posicioneCBTipoIden(String D){
        int n= cbxTipoIdent.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxTipoIdent.getItemAt(i).toString();
            if(D.compareTo(desc)==0){
                cbxTipoIdent.setSelectedIndex(i);
                break;
            }
        }
    }
    
    public void posicioneCBGenero(String genero){
        int n= cbxGenero.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxGenero.getItemAt(i).toString();                      
            if(genero.compareTo(desc)==0){
                cbxGenero.setSelectedIndex(i);
                break;
            }
        }
    }
    
      public void posicioneCBCiudad(String ciudad){
        int n= cbxCiudad.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxCiudad.getItemAt(i).toString();                      
            if(ciudad.compareTo(desc)==0){
                cbxCiudad.setSelectedIndex(i);
                break;
            }
        }
    }
    
    public void posicioneCBEstado(String estado){
        int n= cbxEstado.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxEstado.getItemAt(i).toString();                      
            if(estado.compareTo(desc)==0){
                cbxEstado.setSelectedIndex(i);
                break;
            }
        }
    }  
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre=txtNombre.getText();
        String apellido=txtApellido.getText();
        String numeroDocumento=txtNroDocu.getText().trim();
        String direccion=txtDireccion.getText().trim();
        
        
        if(accionFormCliGui.compareTo("Nuevo")==0){
            if(nombre.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el nombre del cliente"); 
                txtNombre.grabFocus();
                
            }else if(apellido.length()==0){//APELLIDO
                JOptionPane.showMessageDialog(null,"Digite el Apellido del cliente"); 
                txtApellido.grabFocus();
                
            }else if(numeroDocumento.length()==0){//NUMERO DOCUMENTO
                JOptionPane.showMessageDialog(null,"Digite el número de Documento"); 
                txtNroDocu.grabFocus();
                
            }else if(objCtrlCli.existeNumeroID(txtNroDocu.getText())==1){//NUMERO DOCUMENTO UNICO
                JOptionPane.showMessageDialog(null,"Digita otro numero de Documento, ya existe un Cliente con ese numero!"); 
                txtNroDocu.grabFocus();
                
            }else if(direccion.length()==0){//DIRECCION            
                JOptionPane.showMessageDialog(null,"Digite la direccion"); 
                txtDireccion.grabFocus();
                
            }else if(txtEmail.getText().length()!=0 && objCtrlCli.ValidarEmail(txtEmail.getText())==false){            
                JOptionPane.showMessageDialog(null,"Digite un correo valido\nEjemplo: (micorreo@dominio.com)"); 
                txtEmail.grabFocus();
                
            }else{
                guardar();
                limpiar();
                ClienteGui.btnEditarCliente.setEnabled(false);
//                ClienteGui.btnEliminarCliente.setEnabled(false);
                this.dispose();
            }
        }else if(accionFormCliGui.compareTo("Editar")==0){
            if(nombre.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el nombre del cliente"); 
                txtNombre.grabFocus();
                
            }else if(apellido.length()==0){//APELLIDO
                JOptionPane.showMessageDialog(null,"Digite el Apellido del cliente"); 
                txtApellido.grabFocus();
                
            }else if(numeroDocumento.length()==0){//NUMERO DOCUMENTO
                JOptionPane.showMessageDialog(null,"Digite el número de Documento"); 
                txtNroDocu.grabFocus();
                
            }else if(objCtrlCli.existeNumeroIDEditar(txtNroDocu.getText(),
                    ClienteGui.codigoCliente)!=0){            
                JOptionPane.showMessageDialog(null,"Digita otro numero de Documento, ya existe un cliente con ese numero!"); 
                txtNroDocu.grabFocus();
                
            }else if(direccion.length()==0){//DIRECCION            
                JOptionPane.showMessageDialog(null,"Digite la direccion"); 
                txtDireccion.grabFocus();
                
            }else if(txtEmail.getText().length()!=0 && objCtrlCli.ValidarEmail(txtEmail.getText())==false){            
                JOptionPane.showMessageDialog(null,"Digite un correo valido\nEjemplo: (micorreo@dominio.com)"); 
                txtEmail.grabFocus();
                
            }else{
                editar(ClienteGui.codigoCliente);
                ClienteGui.btnEditarCliente.setEnabled(false);
//                ClienteGui.btnEliminarCliente.setEnabled(false);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    public void editar(int codigoCliente){
        
        Cliente objCli=new Cliente();
                    
            //DATOS DE CLIENTE
            objCli.setCodigoCliente(codigoCliente);
            objCli.setNombre(txtNombre.getText());
            objCli.setApellido(txtApellido.getText());
            objCli.setFechaNacimiento(Date.valueOf(getMiFechaNac()));
            objCli.setIdTipoIdentidad(Integer.valueOf(txtIdTipoIden.getText()));
            objCli.setNumeroDocumento(txtNroDocu.getText());
            
            String genero=(String)cbxGenero.getSelectedItem();
                   
            objCli.setGenero(genero);
            objCli.setCodigoCiudad(Integer.valueOf(txtCodiCiudad.getText()));
            objCli.setDireccion(txtDireccion.getText());
            objCli.setTelefono(txtTelefono.getText());
            objCli.setEmail(txtEmail.getText());
            objCli.setEstado(cbxEstado.getSelectedItem().toString());
                        
        if(objCtrlCli.modificar(objCli)){
            JOptionPane.showMessageDialog(null,"Cliente Editado con Exito!");
            borrarJtable();
            ActualizarTablaEnCliGui();
        }else{
            JOptionPane.showMessageDialog(null,"Error al Editar!!!");
        }
        
    }
    
    
    private void cbxTipoIdentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoIdentActionPerformed
        TipoIdentidad ti=(TipoIdentidad) cbxTipoIdent.getSelectedItem();
        String idTipoIdentidad = String.valueOf(ti.getIdTipoIdentidad());
        txtIdTipoIden.setText(idTipoIdentidad);
    }//GEN-LAST:event_cbxTipoIdentActionPerformed

    private void cbxCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCiudadActionPerformed
        Ciudad ciu=(Ciudad)cbxCiudad.getSelectedItem();
        String codigoCiudad=String.valueOf(ciu.getCodigoCiudad());
        txtCodiCiudad.setText(codigoCiudad);
    }//GEN-LAST:event_cbxCiudadActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
         int numCaracteres=60;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtNombre.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 60 caracteres");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        int numCaracteres=60;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtApellido.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 60 caracteres");
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNroDocuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroDocuKeyTyped
       int numCaracteres=20;
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo numeros!");
            txtNroDocu.grabFocus();
        }
        if(txtNroDocu.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 20 caracteres");
        }
    }//GEN-LAST:event_txtNroDocuKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        int numCaracteres=60;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtDireccion.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 60 caracteres");
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
       int numCaracteres=12;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtTelefono.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 12 caracteres");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
       int numCaracteres=150;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtEmail.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 150 caracteres");
        }
    }//GEN-LAST:event_txtEmailKeyTyped
    
     public void guardar(){
        
            Cliente objCli=new Cliente();
                    
            //DATOS DE CLIENTE
            objCli.setNombre(txtNombre.getText());
            objCli.setApellido(txtApellido.getText());
            objCli.setFechaNacimiento(Date.valueOf(getMiFechaNac()));
            objCli.setIdTipoIdentidad(Integer.valueOf(txtIdTipoIden.getText()));
            objCli.setNumeroDocumento(txtNroDocu.getText());
            
            String genero=(String)cbxGenero.getSelectedItem();
                   
            objCli.setGenero(genero);
            objCli.setCodigoCiudad(Integer.valueOf(txtCodiCiudad.getText()));
            objCli.setDireccion(txtDireccion.getText());
            objCli.setTelefono(txtTelefono.getText());
            objCli.setEmail(txtEmail.getText());
            objCli.setEstado(cbxEstado.getSelectedItem().toString());
                
            if(objCtrlCli.guardar(objCli)){
                JOptionPane.showMessageDialog(null,"El cliente se registro con Exito!");
                borrarJtable();
                ActualizarTablaEnCliGui();
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null,"El Cliente NO Fue Registrado!");  
            }      
          }
        
     public String getMiFechaNac(){
        String   fecha="" ;
        int anio=jDateSFechaNac.getCalendar().get(Calendar.YEAR);
        int mes=jDateSFechaNac.getCalendar().get(Calendar.MONTH);
        int dia=jDateSFechaNac.getCalendar().get(Calendar.DAY_OF_MONTH);
        fecha=anio+"-"+(mes+1)+"-"+dia;
        return fecha;
    } 
    
    public void limpiar(){        
        txtNombre.setText("");
        txtApellido.setText("");
        txtIdTipoIden.setText("");
        txtNroDocu.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
    } 
     
    public void ActualizarTablaEnCliGui(){
        modelo=(DefaultTableModel)ClienteGui.tblClientes.getModel();
        elqueOrdena=new TableRowSorter<TableModel>(modelo);
        ClienteGui.tblClientes.setRowSorter(elqueOrdena);//con esto se puede ordenar por col el jtable de manera asc o desc
        CtrlCliente objCtrlCli=new CtrlCliente();
                
        ArrayList<Cliente> listado=new ArrayList();
        listado=objCtrlCli.traerTodosDos();
        Object []col=new Object[modelo.getColumnCount()];//creo un obj tipo Object del tamaño de las columnas de mi Table
                
       for(int index=0;index<listado.size();index++){//recorro el arrayList
            col[0]=listado.get(index).getCodigoCliente();
            col[1]=listado.get(index).getNombre();
            col[2]=listado.get(index).getApellido();
            col[3]=listado.get(index).getNombreTipoIdentidad();
            col[4]=listado.get(index).getNumeroDocumento();
            col[5]=listado.get(index).getFechaNacimiento();
            col[6]=listado.get(index).getGenero();
            col[7]=listado.get(index).getDireccion();            
            col[8]=listado.get(index).getTelefono();
            col[9]=listado.get(index).getEmail();
            col[10]=listado.get(index).getNombreCiu();
            col[11]=listado.get(index).getEstado();
            modelo.addRow(col);//añado el object a la fila
       }
       ClienteGui.tblClientes.setModel(modelo);
    }
    
     private void borrarJtable(){
        modelo=(DefaultTableModel)ClienteGui.tblClientes.getModel();
        for (int i = ClienteGui.tblClientes.getRowCount() -1; i >= 0; i--){ 
                modelo.removeRow(i); 
        }      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormClienteGui dialog = new FormClienteGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbxCiudad;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox cbxGenero;
    private javax.swing.JComboBox cbxTipoIdent;
    private com.toedter.calendar.JDateChooser jDateSFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodiCiudad;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdTipoIden;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroDocu;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
