/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.CtrlCargo;
import Control.CtrlHorarioLaboral;
import Control.CtrlRol;
import Control.CtrlTipoIdentidad;
import Control.CtrlUsuario;
import Modelo.Cargo;
import Modelo.Cliente;
import Modelo.HorarioLaboral;
import Modelo.Rol;
import Modelo.TipoIdentidad;
import Modelo.Usuario;
import com.toedter.calendar.JDateChooser;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JEFERSSON
 */
public class FormUsuarioGui extends javax.swing.JDialog {

     
    CtrlUsuario objCtrlUsu=new CtrlUsuario();
    CtrlTipoIdentidad objCtrlTI=new CtrlTipoIdentidad();
    CtrlRol objCtrlR=new CtrlRol();
    CtrlCargo objCtrlCargo=new CtrlCargo();
    CtrlHorarioLaboral objCtrlHl=new CtrlHorarioLaboral();
    
    
    DefaultTableModel modelo;//modelo de datos
    TableRowSorter<TableModel> elqueOrdena;
    
    String accionFormUsuGui="";
            
    public FormUsuarioGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        jDSFechaNac.setDateFormatString("yyyy-MM-dd");//dar formato a la fecha, por defecto viene dd/MM/yyyy
        ((JTextField) this.jDSFechaNac.getDateEditor()).setEditable(false);//para no editar en el jDateShooser
        txtIdTipoIdentidad.setVisible(false);
        txtIdRol.setVisible(false);
        txtIdCargo.setVisible(false);
        txtIdHorario.setVisible(false);        
        objCtrlTI.cargarCB(cbxTipoIdentidad);
        objCtrlR.cargarCB(cbxNomRol);
        objCtrlCargo.cargarCB(cbxCargo);
        objCtrlHl.cargarCB(cbxHorario);
        accionFormUsuGui=UsuarioGui.ACCIONUSU;
//        
        if(accionFormUsuGui.compareTo("Editar")==0){
            buscar(UsuarioGui.idUsuario);
            btnGuardar.setText("Editar");
        }else if(accionFormUsuGui.compareTo("Nuevo")==0){
            btnGuardar.setText("Guardar");
        }              
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPriNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSegNombre = new javax.swing.JTextField();
        txtPriApellido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSegApellido = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbxTipoIdentidad = new javax.swing.JComboBox();
        txtIdTipoIdentidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNroIdentidad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDSFechaNac = new com.toedter.calendar.JDateChooser();
        cbxNomRol = new javax.swing.JComboBox();
        txtIdRol = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cbxCargo = new javax.swing.JComboBox();
        txtIdCargo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbxHorario = new javax.swing.JComboBox();
        txtIdHorario = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ptxtPassword = new javax.swing.JPasswordField();
        txtHorarioDesc = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ptxtConfirPass = new javax.swing.JPasswordField();
        cbxEstado = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO USUARIO");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("1er Nombre:");

        txtPriNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriNombreKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("2do Nombre:");

        txtSegNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegNombreKeyTyped(evt);
            }
        });

        txtPriApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriApellidoKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("1er Apellido:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("2do Apellido:");

        txtSegApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegApellidoKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tipo Identidad:");

        cbxTipoIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoIdentidadActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nro Identidad:");

        txtNroIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroIdentidadKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Sexo:");

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Fecha Nto:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Rol:");

        cbxNomRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomRolActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Cargo:");

        cbxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCargoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Horario:");

        cbxHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHorarioActionPerformed(evt);
            }
        });

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Direccion:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Telefono:");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Login:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Password:");

        ptxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ptxtPasswordKeyTyped(evt);
            }
        });

        txtHorarioDesc.setEditable(false);
        txtHorarioDesc.setBackground(new java.awt.Color(204, 204, 204));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Desc Horario:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Confirmar Password:");

        ptxtConfirPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ptxtConfirPassKeyTyped(evt);
            }
        });

        cbxEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Estado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtNroIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtSegApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtPriApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtSegNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPriNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDSFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102))
                                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdTipoIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel18)
                            .addComponent(jLabel25)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)))
                    .addComponent(jLabel26))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ptxtConfirPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHorarioDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ptxtPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxNomRol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdRol, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPriNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSegNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPriApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSegApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cbxNomRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(cbxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHorarioDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cbxTipoIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdTipoIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNroIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDSFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(ptxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ptxtConfirPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addComponent(cbxEstado))
                    .addComponent(jLabel4))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(25, 115, 14));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(224, 79, 37));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(693, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(26, 26, 26)
                .addComponent(btnGuardar)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void buscar(int idUsuario){
        ArrayList<Usuario> usuario=new ArrayList();
        usuario=objCtrlUsu.traerUnUsuario(idUsuario);
        int tam=usuario.size();
        String horarioLaboral="";
        
        for(int index=0;index<tam;index++){
            txtPriNombre.setText(usuario.get(index).getPrimerNombre());
            txtSegNombre.setText(usuario.get(index).getSegundoNombre());
            txtPriApellido.setText(usuario.get(index).getPrimerApellido());
            txtSegApellido.setText(usuario.get(index).getSegundoApellido());
            posicioneCBTipoIden(usuario.get(index).getNombreTipoIdentidad());
            txtNroIdentidad.setText(usuario.get(index).getNumeroIdentidad());
            posicioneCBSexo(usuario.get(index).getSexo());
            jDSFechaNac.setDate(usuario.get(index).getFechaNac());
            posicioneCBRol(usuario.get(index).getNomRol());
            posicioneCBCargo(usuario.get(index).getNomCargo());
            horarioLaboral=usuario.get(index).getHorarioLaboral().getHoraInicio()+" a "+usuario.get(index).getHorarioLaboral().getHoraFin();
            posicioneCBHorario(horarioLaboral);           
            txtDireccion.setText(usuario.get(index).getDireccion());
            txtTelefono.setText(usuario.get(index).getTelefono());
            txtLogin.setText(usuario.get(index).getLogin());
            ptxtPassword.setText(usuario.get(index).getPassword());
            posicioneCBEstado(usuario.get(index).getEstado());
        }
    }
    
    public void posicioneCBTipoIden(String D){
        int n= cbxTipoIdentidad.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxTipoIdentidad.getItemAt(i).toString();
            if(D.compareTo(desc)==0){
                cbxTipoIdentidad.setSelectedIndex(i);
                break;
            }
        }
    }
    
    public void posicioneCBSexo(String genero){
        int n= cbxSexo.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxSexo.getItemAt(i).toString();                      
            if(genero.compareTo(desc)==0){
                cbxSexo.setSelectedIndex(i);
                break;
            }
        }
    }
    
      public void posicioneCBRol(String rol){
        int n= cbxNomRol.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxNomRol.getItemAt(i).toString();                      
            if(rol.compareTo(desc)==0){
                cbxNomRol.setSelectedIndex(i);
                break;
            }
        }
    }
      
    public void posicioneCBCargo(String cargo){
        int n= cbxCargo.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxCargo.getItemAt(i).toString();                      
            if(cargo.compareTo(desc)==0){
                cbxCargo.setSelectedIndex(i);
                break;
            }
        }
    }  
    
    public void posicioneCBHorario(String horario){
        int n= cbxHorario.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxHorario.getItemAt(i).toString();                      
            if(horario.compareTo(desc)==0){
                cbxHorario.setSelectedIndex(i);
                break;
            }
        }
    } 
    
    public void posicioneCBEstado(String estado){
        int n= cbxEstado.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxEstado.getItemAt(i).toString();                      
            if(estado.compareTo(desc)==0){
                cbxEstado.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String primerNombre=txtPriNombre.getText();
        String primerApellido=txtPriApellido.getText();
        String numeroDocumento=txtNroIdentidad.getText();
        String login=txtLogin.getText();
        String password=ptxtPassword.getText();
        String confirPass=ptxtConfirPass.getText();
        
        if(accionFormUsuGui.compareTo("Nuevo")==0){
            
            if(primerNombre.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite su primer Nombre","Error",JOptionPane.ERROR_MESSAGE); 
                txtPriNombre.grabFocus();
                
            }else if(primerApellido.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite su primer Apellido","Error",JOptionPane.ERROR_MESSAGE); 
                txtPriApellido.grabFocus();
                
            }else if(numeroDocumento.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite su numero de Documento","Error",JOptionPane.ERROR_MESSAGE); 
                txtNroIdentidad.grabFocus();
                
            }else if(objCtrlUsu.existeNumeroID(txtNroIdentidad.getText())!=0){            
                JOptionPane.showMessageDialog(null,"Digita otro numero de identidad, ya existe un Usuario con ese numero!","Error",JOptionPane.ERROR_MESSAGE); 
                txtNroIdentidad.grabFocus();
                
            }else if(jDSFechaNac.getDate()==null){//VALIDAR FECHA
                JOptionPane.showMessageDialog(null,"Escoja la Fecha de Nacimiento","Error",JOptionPane.ERROR_MESSAGE); 
                jDSFechaNac.requestFocus();
                
            }else if(login.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite un Login","Error",JOptionPane.ERROR_MESSAGE); 
                txtLogin.grabFocus();
                
            }else if(objCtrlUsu.existeLogin(txtLogin.getText())!=0){            
                JOptionPane.showMessageDialog(null,"Otro Usuario ya tiene ese Login, digite otro diferente!","Error",JOptionPane.ERROR_MESSAGE); 
                txtLogin.grabFocus();
                
            }else if(password.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite un Password","Error",JOptionPane.ERROR_MESSAGE); 
                ptxtPassword.grabFocus();
                
            }else if(password.compareTo(confirPass)!=0){//NOMBRE
                JOptionPane.showMessageDialog(null,"No coindice el Password!","Error",JOptionPane.ERROR_MESSAGE); 
                ptxtConfirPass.grabFocus();
                
            }else{
                guardar();
                limpiar();
                UsuarioGui.btnEditarUsuario.setEnabled(false);
//                UsuarioGui.btnEliminarUsuario.setEnabled(false);
                this.dispose();
            }
        }else if(accionFormUsuGui.compareTo("Editar")==0){
            
            if(primerNombre.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite su primer Nombre","Error",JOptionPane.ERROR_MESSAGE); 
                txtPriNombre.grabFocus();
                
            }else if(primerApellido.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite su primer Apellido","Error",JOptionPane.ERROR_MESSAGE); 
                txtPriApellido.grabFocus();
                
            }else if(numeroDocumento.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite su numero de Documento","Error",JOptionPane.ERROR_MESSAGE); 
                txtNroIdentidad.grabFocus();
                
            }else if(objCtrlUsu.existeNumeroIDEditar(txtNroIdentidad.getText(),
                    UsuarioGui.idUsuario)!=0){            
                JOptionPane.showMessageDialog(null,"Digita otro numero de identidad, ya existe un Usuario con ese numero!","Error",JOptionPane.ERROR_MESSAGE); 
                txtNroIdentidad.grabFocus();
                
            }else if(jDSFechaNac.getDate()==null){//VALIDAR FECHA
                JOptionPane.showMessageDialog(null,"Escoja la Fecha de Nacimiento","Error",JOptionPane.ERROR_MESSAGE); 
                jDSFechaNac.requestFocus();
                
            }else if(login.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite un Login","Error",JOptionPane.ERROR_MESSAGE); 
                txtLogin.grabFocus();
                
            }else if(objCtrlUsu.existeLoginEditar(txtLogin.getText(),UsuarioGui.idUsuario)!=0){            
                JOptionPane.showMessageDialog(null,"Otro Usuario ya tiene ese Login, digite otro diferente!","Error",JOptionPane.ERROR_MESSAGE); 
                txtLogin.grabFocus();
                
            }else if(password.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite un Password","Error",JOptionPane.ERROR_MESSAGE); 
                ptxtPassword.grabFocus();
                
            }else if(password.compareTo(confirPass)!=0){//NOMBRE
                JOptionPane.showMessageDialog(null,"No coindice el Password!","Error",JOptionPane.ERROR_MESSAGE); 
                ptxtConfirPass.grabFocus();
                
            }else{    
                editar(UsuarioGui.idUsuario);
                UsuarioGui.btnEditarUsuario.setEnabled(false);
//                UsuarioGui.btnEliminarUsuario.setEnabled(false);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void ptxtConfirPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptxtConfirPassKeyTyped
        int numCaracteres=50;
        //System.out.print("-->"+letra_text.getText().length());
        if(ptxtConfirPass.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 50 caracteres");
        }
    }//GEN-LAST:event_ptxtConfirPassKeyTyped

    private void ptxtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptxtPasswordKeyTyped
        int numCaracteres=50;
        //System.out.print("-->"+letra_text.getText().length());
        if(ptxtPassword.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 50 caracteres");
        }
    }//GEN-LAST:event_ptxtPasswordKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        int numCaracteres=12;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtTelefono.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 12 caracteres");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        int numCaracteres=60;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtDireccion.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 60 caracteres");
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void cbxHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHorarioActionPerformed
        HorarioLaboral hl=(HorarioLaboral)cbxHorario.getSelectedItem();
        String idHorario=String.valueOf(hl.getIdHorario());
        txtIdHorario.setText(idHorario);
        txtHorarioDesc.setText(hl.getHoraDesc());
    }//GEN-LAST:event_cbxHorarioActionPerformed

    private void cbxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCargoActionPerformed
        Cargo car=(Cargo)cbxCargo.getSelectedItem();
        String idCargo=String.valueOf(car.getIdCargo());
        txtIdCargo.setText(idCargo);
    }//GEN-LAST:event_cbxCargoActionPerformed

    private void cbxNomRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomRolActionPerformed
        Rol r=(Rol)cbxNomRol.getSelectedItem();
        String idRol=String.valueOf(r.getIdRol());
        txtIdRol.setText(idRol);
    }//GEN-LAST:event_cbxNomRolActionPerformed

    private void txtNroIdentidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroIdentidadKeyTyped
        int numCaracteres=30;
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo numeros!");
            txtNroIdentidad.grabFocus();
        }
        if(txtNroIdentidad.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 30 caracteres");
        }
    }//GEN-LAST:event_txtNroIdentidadKeyTyped

    private void cbxTipoIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoIdentidadActionPerformed
        TipoIdentidad ti=(TipoIdentidad)cbxTipoIdentidad.getSelectedItem();
        String idTipoIdentidad=String.valueOf(ti.getIdTipoIdentidad());
        txtIdTipoIdentidad.setText(idTipoIdentidad);
    }//GEN-LAST:event_cbxTipoIdentidadActionPerformed

    private void txtSegApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegApellidoKeyTyped
        int numCaracteres=30;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtSegApellido.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 30 caracteres");
        }
    }//GEN-LAST:event_txtSegApellidoKeyTyped

    private void txtPriApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriApellidoKeyTyped
        int numCaracteres=30;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtPriApellido.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 30 caracteres");
        }
    }//GEN-LAST:event_txtPriApellidoKeyTyped

    private void txtSegNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegNombreKeyTyped
        int numCaracteres=30;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtSegNombre.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 30 caracteres");
        }
    }//GEN-LAST:event_txtSegNombreKeyTyped

    private void txtPriNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriNombreKeyTyped
        int numCaracteres=30;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtPriNombre.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 30 caracteres");
        }
    }//GEN-LAST:event_txtPriNombreKeyTyped
    
    public void editar(int idUsuario){
        
         Usuario objUsu=new Usuario();
                    
            //DATOS DE USUARIO
            objUsu.setIdUsuario(idUsuario);
             objUsu.setPrimerNombre(txtPriNombre.getText());
             objUsu.setSegundoNombre(txtSegNombre.getText());
             objUsu.setPrimerApellido(txtPriApellido.getText());
             objUsu.setSegundoApellido(txtSegApellido.getText());
             objUsu.setIdTipoIdentidad(Integer.valueOf(txtIdTipoIdentidad.getText()));
             objUsu.setNumeroIdentidad(txtNroIdentidad.getText());
             objUsu.setSexo(cbxSexo.getSelectedItem().toString());
             objUsu.setFechaNac(Date.valueOf(getMiFechaNac()));
             objUsu.setIdRol(Integer.valueOf(txtIdRol.getText()));
             objUsu.setIdCargo(Integer.valueOf(txtIdCargo.getText()));
                HorarioLaboral hl=new HorarioLaboral();
                hl.setIdHorario(Integer.valueOf(txtIdHorario.getText()));                            
             objUsu.setHorarioLaboral(hl);
             objUsu.setDireccion(txtDireccion.getText());
             objUsu.setTelefono(txtTelefono.getText());
             objUsu.setLogin(txtLogin.getText());
             objUsu.setPassword(ptxtPassword.getText());
             objUsu.setEstado(cbxEstado.getSelectedItem().toString());           
        if(objCtrlUsu.modificar(objUsu)){
            JOptionPane.showMessageDialog(null,"Usuario Editado con Exito!");
            borrarJtable();
            ActualizarTablaEnUsuGui();
        }else{
            JOptionPane.showMessageDialog(null,"Error al Editar!!!");
        }
        
    }
    
        
     public void guardar(){
        
            Usuario objUsu=new Usuario();
                    
            //DATOS DE USUARIO
             objUsu.setPrimerNombre(txtPriNombre.getText());
             objUsu.setSegundoNombre(txtSegNombre.getText());
             objUsu.setPrimerApellido(txtPriApellido.getText());
             objUsu.setSegundoApellido(txtSegApellido.getText());
             objUsu.setIdTipoIdentidad(Integer.valueOf(txtIdTipoIdentidad.getText()));
             objUsu.setNumeroIdentidad(txtNroIdentidad.getText());
             objUsu.setSexo(cbxSexo.getSelectedItem().toString());
             objUsu.setFechaNac(Date.valueOf(getMiFechaNac()));
             objUsu.setIdRol(Integer.valueOf(Integer.valueOf(txtIdRol.getText())));
             objUsu.setIdCargo(Integer.valueOf(txtIdCargo.getText()));
                HorarioLaboral hl=new HorarioLaboral();
                hl.setIdHorario(Integer.valueOf(Integer.valueOf(txtIdHorario.getText())));                            
             objUsu.setHorarioLaboral(hl);
             objUsu.setDireccion(txtDireccion.getText());
             objUsu.setTelefono(txtTelefono.getText());
             objUsu.setLogin(txtLogin.getText());
             objUsu.setPassword(ptxtPassword.getText());
             objUsu.setEstado(cbxEstado.getSelectedItem().toString());
             
             if(objCtrlUsu.guardar(objUsu)){
                JOptionPane.showMessageDialog(null,"El Usuario se registro con Exito!");
                borrarJtable();
                ActualizarTablaEnUsuGui();
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null,"El Usuario NO Fue Registrado!");  
            }      
          }
        
     public String getMiFechaNac(){
        String   fecha="" ;
        int anio=jDSFechaNac.getCalendar().get(Calendar.YEAR);
        int mes=jDSFechaNac.getCalendar().get(Calendar.MONTH);
        int dia=jDSFechaNac.getCalendar().get(Calendar.DAY_OF_MONTH);
        fecha=anio+"-"+(mes+1)+"-"+dia;
        return fecha;
    } 
    
    public void limpiar(){        
        txtPriNombre.setText("");
        txtSegNombre.setText("");
        txtPriApellido.setText("");
        txtSegApellido.setText("");        
        txtNroIdentidad.setText("");
        jDSFechaNac.setDate(null);
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtLogin.setText("");
        ptxtPassword.setText("");
    } 
     
    public void ActualizarTablaEnUsuGui(){
        modelo=(DefaultTableModel)UsuarioGui.tblUsuarios.getModel();
        elqueOrdena=new TableRowSorter<TableModel>(modelo);
        UsuarioGui.tblUsuarios.setRowSorter(elqueOrdena);//con esto se puede ordenar por col el jtable de manera asc o desc
        
                
        ArrayList<Usuario> listado=new ArrayList();
        listado=objCtrlUsu.listadoUsuarios();
        Object []col=new Object[modelo.getColumnCount()];//creo un obj tipo Object del tamaño de las columnas de mi Table
        String horarioLaboral="";        
       for(int index=0;index<listado.size();index++){//recorro el arrayList
            col[0]=listado.get(index).getIdUsuario();
            col[1]=listado.get(index).getPrimerNombre();
            col[2]=listado.get(index).getSegundoNombre();
            col[3]=listado.get(index).getPrimerApellido();
            col[4]=listado.get(index).getSegundoApellido();
            col[5]=listado.get(index).getNombreTipoIdentidad();
            col[6]=listado.get(index).getNumeroIdentidad();
            col[7]=listado.get(index).getSexo();            
            col[8]=listado.get(index).getFechaNac();
            col[9]=listado.get(index).getNomRol();            
            col[10]=listado.get(index).getNomCargo();
            horarioLaboral=listado.get(index).getHorarioLaboral().getHoraInicio()+" - "+listado.get(index).getHorarioLaboral().getHoraFin();
            
            col[11]=horarioLaboral;
            col[12]=listado.get(index).getDireccion();            
            col[13]=listado.get(index).getTelefono();
            col[14]=listado.get(index).getLogin();
            col[15]=listado.get(index).getEstado();
            modelo.addRow(col);//añado el object a la fila
       }
       UsuarioGui.tblUsuarios.setModel(modelo);
    }
    
     private void borrarJtable(){
        modelo=(DefaultTableModel)UsuarioGui.tblUsuarios.getModel();
        for (int i = UsuarioGui.tblUsuarios.getRowCount() -1; i >= 0; i--){ 
                modelo.removeRow(i); 
        }      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuarioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormUsuarioGui dialog = new FormUsuarioGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbxCargo;
    private javax.swing.JComboBox cbxEstado;
    private javax.swing.JComboBox cbxHorario;
    private javax.swing.JComboBox cbxNomRol;
    private javax.swing.JComboBox cbxSexo;
    private javax.swing.JComboBox cbxTipoIdentidad;
    private com.toedter.calendar.JDateChooser jDSFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField ptxtConfirPass;
    private javax.swing.JPasswordField ptxtPassword;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtHorarioDesc;
    private javax.swing.JTextField txtIdCargo;
    private javax.swing.JTextField txtIdHorario;
    private javax.swing.JTextField txtIdRol;
    private javax.swing.JTextField txtIdTipoIdentidad;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNroIdentidad;
    private javax.swing.JTextField txtPriApellido;
    private javax.swing.JTextField txtPriNombre;
    private javax.swing.JTextField txtSegApellido;
    private javax.swing.JTextField txtSegNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
