/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.CtrlCiudad;
import Control.CtrlProveedor;
import Modelo.Ciudad;
import Modelo.Proveedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JEFERSSON
 */
public class FormProveedorGui extends javax.swing.JDialog {

     
    CtrlProveedor objCtrlProve=new CtrlProveedor();    
    CtrlCiudad objCtrlCiu=new CtrlCiudad();
    
    DefaultTableModel modelo;//modelo de datos
    TableRowSorter<TableModel> elqueOrdena;
    
    String accionFormProveGui="";
            
    public FormProveedorGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        txtCodiCiudad.setVisible(false);
        setLocationRelativeTo(null);        
        objCtrlCiu.cargarCB(cbxCiudad);        
        accionFormProveGui=ProveedorGui.ACCIONPROVE;
        
        if(accionFormProveGui.compareTo("Editar")==0){
            buscar(ProveedorGui.idProveedores);
            btnGuardar.setText("Editar");
        }else if(accionFormProveGui.compareTo("Nuevo")==0){
            btnGuardar.setText("Guardar");
        }              
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNumeroIdentidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxCiudad = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCodiCiudad = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO PROVEEDOR");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario Proveedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtNumeroIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroIdentidadKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Numero Documento");

        cbxCiudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCiudadActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ciudad:");

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Direccion:");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Telefono:");

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Email:");

        txtCodiCiudad.setEditable(false);

        cbxEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Estado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEmail)
                        .addComponent(txtNumeroIdentidad)
                        .addComponent(txtNombre)
                        .addComponent(txtDireccion)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(cbxCiudad, 0, 183, Short.MAX_VALUE)
                            .addGap(38, 38, 38)
                            .addComponent(txtCodiCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtTelefono))
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodiCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(25, 115, 14));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(224, 79, 37));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void buscar(int idProveedores){
        ArrayList<Proveedor> listado=new ArrayList();
        listado=objCtrlProve.traerUnProveedor(idProveedores);
        int tam=listado.size();
        
        for(int index=0;index<tam;index++){
            txtNombre.setText(listado.get(index).getNombre());
            txtNumeroIdentidad.setText(String.valueOf(listado.get(index).getNumeroIdentidad()));                   
            posicioneCBCiudad(listado.get(index).getNomCiudad());
            txtDireccion.setText(listado.get(index).getDireccion());
            txtTelefono.setText(listado.get(index).getTelefono());
            txtEmail.setText(listado.get(index).getEmail());
            posicioneCBEstado(listado.get(index).getEstado());
            
        }
    }
    
 
    public void posicioneCBCiudad(String ciudad){
        int n= cbxCiudad.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxCiudad.getItemAt(i).toString();                      
            if(ciudad.compareTo(desc)==0){
                cbxCiudad.setSelectedIndex(i);
                break;
            }
        }
    }
    
    public void posicioneCBEstado(String estado){
        int n= cbxEstado.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxEstado.getItemAt(i).toString();                      
            if(estado.compareTo(desc)==0){
                cbxEstado.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            String nombre=txtNombre.getText().trim();                      
            String numeroIdentidad=txtNumeroIdentidad.getText().trim(); 
            String direccion=txtDireccion.getText().trim();
           //confirma si ya existe ese numero identidad
        if(accionFormProveGui.compareTo("Nuevo")==0){
            
            if(nombre.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el nombre del proveedor","Error",JOptionPane.ERROR_MESSAGE); 
                txtNombre.grabFocus();
                
            }else if(numeroIdentidad.length()==0){//NUMEROIDENTIDAD
                JOptionPane.showMessageDialog(null,"Digite el numero de Identidad","Error",JOptionPane.ERROR_MESSAGE);
                txtNumeroIdentidad.grabFocus();
                
            }else if(objCtrlProve.existeNumeroID(txtNumeroIdentidad.getText())==1){            
                JOptionPane.showMessageDialog(null,"Digita otro numero de identidad, ya existe un proveedor con ese numero!","Error",JOptionPane.ERROR_MESSAGE); 
                txtNumeroIdentidad.grabFocus();
                
            }else if(direccion.length()==0){            
                JOptionPane.showMessageDialog(null,"Digite la direccion","Error",JOptionPane.ERROR_MESSAGE); 
                txtDireccion.grabFocus();
                
            }else if(txtEmail.getText().length()!=0 && objCtrlProve.ValidarEmail(txtEmail.getText())==false){            
                JOptionPane.showMessageDialog(null,"Digite un correo valido\nEjemplo: (micorreo@dominio.com)","Error",JOptionPane.ERROR_MESSAGE); 
                txtEmail.grabFocus();
                
            }else{
                guardar();
                limpiar();
                ProveedorGui.btnEditarProvee.setEnabled(false);
//                ProveedorGui.btnEliminarProvee.setEnabled(false);
                this.dispose();
            }
        }else if(accionFormProveGui.compareTo("Editar")==0){
                if(nombre.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el nombre del proveedor","Error",JOptionPane.ERROR_MESSAGE); 
                txtNombre.grabFocus();
                
            }else if(numeroIdentidad.length()==0){//NUMEROIDENTIDAD
                JOptionPane.showMessageDialog(null,"Digite el numero de Identidad","Error",JOptionPane.ERROR_MESSAGE);
                txtNumeroIdentidad.grabFocus();
                
            }else if(objCtrlProve.existeNumeroIDEditar(txtNumeroIdentidad.getText(),
                    ProveedorGui.idProveedores)!=0){            
                JOptionPane.showMessageDialog(null,"Digita otro numero de identidad, ya existe un proveedor con ese numero!","Error",JOptionPane.ERROR_MESSAGE); 
                txtNumeroIdentidad.grabFocus();
                
            }else if(direccion.length()==0){            
                JOptionPane.showMessageDialog(null,"Digite la direccion"); 
                txtDireccion.grabFocus();
                
            }else if(txtEmail.getText().length()!=0 && objCtrlProve.ValidarEmail(txtEmail.getText())==false){            
                JOptionPane.showMessageDialog(null,"Digite un correo valido\nEjemplo: (micorreo@dominio.com)","Error",JOptionPane.ERROR_MESSAGE); 
                txtEmail.grabFocus();
                
            }else{
                
                editar(ProveedorGui.idProveedores);
                ProveedorGui.btnEditarProvee.setEnabled(false);
//                ProveedorGui.btnEliminarProvee.setEnabled(false);
                this.dispose();
            }  
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    public void editar(int idProveedores){
        
        Proveedor objProve=new Proveedor();
                    
            //DATOS DE PROVEEDOR
            objProve.setIdProveedor(idProveedores);
            objProve.setNombre(txtNombre.getText());
            objProve.setNumeroIdentidad(txtNumeroIdentidad.getText());           
            objProve.setCodigoCiudad(Integer.valueOf(txtCodiCiudad.getText()));
            objProve.setDireccion(txtDireccion.getText());
            objProve.setTelefono(txtTelefono.getText());
            objProve.setEmail(txtEmail.getText());
            objProve.setEstado(cbxEstado.getSelectedItem().toString());            
        if(objCtrlProve.modificar(objProve)){
            JOptionPane.showMessageDialog(null,"Proveeedor Editado con Exito!");
            borrarJtable();
            ActualizarTablaEnCliGui();
        }else{
            JOptionPane.showMessageDialog(null,"Error al Editar!!!");
        }
        
    }
    
    
    private void cbxCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCiudadActionPerformed
        Ciudad ciu=(Ciudad)cbxCiudad.getSelectedItem();
        String codigoCiudad=String.valueOf(ciu.getCodigoCiudad());
        txtCodiCiudad.setText(codigoCiudad);
    }//GEN-LAST:event_cbxCiudadActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        int numCaracteres=80;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtNombre.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 80 caracteres");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNumeroIdentidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroIdentidadKeyTyped
        int numCaracteres=20;
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo numeros!");
            txtNumeroIdentidad.grabFocus();
        }
        
        if(txtNumeroIdentidad.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 20 caracteres");
        }
    }//GEN-LAST:event_txtNumeroIdentidadKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        int numCaracteres=80;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtDireccion.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 80 caracteres");
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        int numCaracteres=12;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtTelefono.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 12 caracteres");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
       int numCaracteres=40;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtEmail.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 40 caracteres");
        }
    }//GEN-LAST:event_txtEmailKeyTyped
    
     public void guardar(){
        
                Proveedor objProve=new Proveedor();                    
                //DATOS DE PROVEEDOR            
                objProve.setNombre(txtNombre.getText());
                objProve.setNumeroIdentidad(txtNumeroIdentidad.getText());           
                objProve.setCodigoCiudad(Integer.valueOf(txtCodiCiudad.getText()));
                objProve.setDireccion(txtDireccion.getText());
                objProve.setTelefono(txtTelefono.getText());
                objProve.setEmail(txtEmail.getText());
                objProve.setEstado(cbxEstado.getSelectedItem().toString());
                  if(objCtrlProve.guardar(objProve)){
                        JOptionPane.showMessageDialog(null,"El proveedor se registro con Exito!");
                        borrarJtable();
                        ActualizarTablaEnCliGui();
                        limpiar();
                  }else{
                      JOptionPane.showMessageDialog(null,"El proveedor NO Fue Registrado!");  
                  } 
                  
    }
        

    
    public void limpiar(){        
        txtNombre.setText("");
        txtNumeroIdentidad.setText("");     
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
    } 
     
    public void ActualizarTablaEnCliGui(){
        modelo=(DefaultTableModel)ProveedorGui.tblProveedores.getModel();
        elqueOrdena=new TableRowSorter<TableModel>(modelo);
        ProveedorGui.tblProveedores.setRowSorter(elqueOrdena);//con esto se puede ordenar por col el jtable de manera asc o desc
        CtrlProveedor objCtrlProve=new CtrlProveedor();
                
        ArrayList<Proveedor> listado=new ArrayList();
        listado=objCtrlProve.traerTodos();
        Object []col=new Object[modelo.getColumnCount()];//creo un obj tipo Object del tamaño de las columnas de mi Table
                
       for(int index=0;index<listado.size();index++){//recorro el arrayList
            col[0]=listado.get(index).getIdProveedor();
            col[1]=listado.get(index).getNombre();
            col[2]=listado.get(index).getNumeroIdentidad();
            col[3]=listado.get(index).getNomCiudad();
            col[4]=listado.get(index).getDireccion();            
            col[5]=listado.get(index).getTelefono();
            col[6]=listado.get(index).getEmail();
            col[7]=listado.get(index).getEstado();
            modelo.addRow(col);//añado el object a la fila
       }
       ProveedorGui.tblProveedores.setModel(modelo);
    }
    
     private void borrarJtable(){
        modelo=(DefaultTableModel)ProveedorGui.tblProveedores.getModel();
        for (int i = ProveedorGui.tblProveedores.getRowCount() -1; i >= 0; i--){ 
                modelo.removeRow(i); 
        }      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormClienteGui dialog = new FormClienteGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbxCiudad;
    private javax.swing.JComboBox cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCodiCiudad;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroIdentidad;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
