/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Control.CtrlArticulo;
import Control.CtrlLineaProducto;
import Control.CtrlProveedor;
import Control.CtrlSubLinea;
import Modelo.Articulo;
import Modelo.LineaProducto;
import Modelo.Proveedor;
import Modelo.SubLineaProducto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JEFERSSON
 */
public class FormArticuloGui extends javax.swing.JDialog {

     
    CtrlArticulo objCtrlArti=new CtrlArticulo();
    CtrlProveedor objCtrlProvee=new CtrlProveedor();
    CtrlSubLinea objCtrlSubLi=new CtrlSubLinea();
    CtrlLineaProducto objCtrlLP=new CtrlLineaProducto();
    DefaultTableModel modelo;//modelo de datos
    TableRowSorter<TableModel> elqueOrdena;
    
    String accionFormArtiGui="";
    
    static int codigoArticuloBD=0;
    static int idSubLineaBD=0;
            
    public FormArticuloGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtIdProveedores.setVisible(false);
        txtIdSubLinea.setVisible(false);
        setLocationRelativeTo(null);
        objCtrlProvee.cargarCB(cbxProveedor);
        objCtrlLP.cargarCB(cbxLineaArticulo);//COMOBOX DE LINEA ARTICULO
        //AUTOMATICAMENTE ME POSICIONA EL COMOBOX DE SUB LINEA PRODUCTO(CONDICIONADO)        
        accionFormArtiGui=ArticulosGui.ACCIONMODARTI;
        
        if(accionFormArtiGui.compareTo("Editar")==0){
            buscar(ArticulosGui.codigoArticuloMod);
            btnGuardar.setText("Editar");
        }else if(accionFormArtiGui.compareTo("Nuevo")==0){
            btnGuardar.setText("Guardar");
            
        }              
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbxSubLinea = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txDescripcion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        txtCosto = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIdProveedores = new javax.swing.JTextField();
        txtIdSubLinea = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbxLineaArticulo = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO ARTICULO");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario Articulo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descripcion:");

        cbxProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProveedorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Proveedor:");

        cbxSubLinea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxSubLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSubLineaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Sub Linea Articulo:");

        txtLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLoteKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Lote:");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cantidad:");

        txDescripcion.setColumns(20);
        txDescripcion.setRows(5);
        txDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txDescripcion);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Valores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        txtCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoKeyTyped(evt);
            }
        });

        txtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Precio Venta:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Costo:");

        txtIva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIvaKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Porcentaje Iva:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(13, 13, 13))
                        .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        txtIdProveedores.setEditable(false);

        txtIdSubLinea.setEditable(false);

        cbxEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Estado:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Linea Articulo:");

        cbxLineaArticulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxLineaArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLineaArticuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtNombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbxLineaArticulo, javax.swing.GroupLayout.Alignment.LEADING, 0, 280, Short.MAX_VALUE)
                                            .addComponent(cbxProveedor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbxSubLinea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtIdProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdSubLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 139, Short.MAX_VALUE)))
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(cbxProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtIdProveedores))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cbxLineaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxSubLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(txtIdSubLinea))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        btnGuardar.setBackground(new java.awt.Color(25, 115, 14));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(224, 79, 37));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void buscar(int codigoCliente){
        ArrayList<Articulo> listado=new ArrayList();
        listado=objCtrlArti.traerUnArticulo(codigoCliente);
        int tam=listado.size();
        
        for(int index=0;index<tam;index++){
             //DATOS DE ARTICULO
            txtNombre.setText(listado.get(index).getNombreArticulo());
            txDescripcion.setText(listado.get(index).getDescripcion());
            posicioneCBProvee(listado.get(index).getNomProvee());            
            posicioneCBLineaProducto(listado.get(index).getSublineaProducto().getDescLineaProd());
            posicioneCBSubLinea(listado.get(index).getSublineaProducto().getSubLineaDescripcion());            
            txtLote.setText(listado.get(index).getLote());
            txtCantidad.setText(String.valueOf(listado.get(index).getCantidad()));
            txtIva.setText(String.valueOf(listado.get(index).getIva()));
            txtCosto.setText(String.valueOf(listado.get(index).getCosto())); 
            txtPrecioVenta.setText(String.valueOf(listado.get(index).getPrecioVenta())); 
            posicioneCBEstado(listado.get(index).getEstado());
                 
        }
    }
    
    public void posicioneCBProvee(String provee){
        int n= cbxProveedor.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxProveedor.getItemAt(i).toString();
            if(provee.compareTo(desc)==0){
                cbxProveedor.setSelectedIndex(i);
                break;
            }
        }
    }
    
    public void posicioneCBSubLinea(String subLinea){
        int n= cbxSubLinea.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxSubLinea.getItemAt(i).toString();                      
            if(subLinea.compareTo(desc)==0){
                cbxSubLinea.setSelectedIndex(i);
                break;
            }
        }
    }
    
    public void posicioneCBLineaProducto(String subLinea){
        int n= cbxLineaArticulo.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxLineaArticulo.getItemAt(i).toString();                      
            if(subLinea.compareTo(desc)==0){
                cbxLineaArticulo.setSelectedIndex(i);
                break;
            }
        }
    }
    public void posicioneCBEstado(String estado){
        int n= cbxEstado.getItemCount();
        String desc="";
        for(int i=0;i<n;i++){
            desc=cbxEstado.getItemAt(i).toString();                      
            if(estado.compareTo(desc)==0){
                cbxEstado.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre=txtNombre.getText();
        String cantidad=txtCantidad.getText(); 
        String porcenIva=txtIva.getText();        
        String costo=txtCosto.getText();
        String precioVenta=txtPrecioVenta.getText();
        
        if(accionFormArtiGui.compareTo("Nuevo")==0){
            
            if(nombre.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el nombre del Articulo"); 
                txtNombre.grabFocus();                
            }else if(cantidad.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite la cantidad del Articulo"); 
                txtCantidad.grabFocus();                
            }else if(porcenIva.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el porcentaje de Iva del Articulo"); 
                txtIva.grabFocus();                
            }else if(costo.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el costo del Articulo"); 
                txtCosto.grabFocus();                
            }else if(precioVenta.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el precio de Venta del Articulo"); 
                txtPrecioVenta.grabFocus();                
            }else{
                guardar();
                limpiar();
                ArticulosGui.btnEditarModArticulo.setEnabled(false);
//                ArticulosGui.btnEliminarModArticulo.setEnabled(false); 
                this.dispose();
            }
            
            
        }else if(accionFormArtiGui.compareTo("Editar")==0){
            
            if(nombre.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el nombre del Articulo"); 
                txtNombre.grabFocus();                
            }else if(cantidad.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite la cantidad del Articulo"); 
                txtCantidad.grabFocus();                
            }else if(porcenIva.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el porcentaje de Iva del Articulo"); 
                txtIva.grabFocus();                
            }else if(costo.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el costo del Articulo"); 
                txtCosto.grabFocus();                
            }else if(precioVenta.length()==0){//NOMBRE
                JOptionPane.showMessageDialog(null,"Digite el precio de Venta del Articulo"); 
                txtPrecioVenta.grabFocus();                
            }else{
                editar(ArticulosGui.codigoArticuloMod);
                ArticulosGui.btnEditarModArticulo.setEnabled(false);
//                ArticulosGui.btnEliminarModArticulo.setEnabled(false);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    public void editar(int codigoArticulo){
        
        Articulo objArti=new Articulo();
          double utilidad=0.0;         
             //DATOS DE ARTICULO
            objArti.setCodigoArticulo(codigoArticulo);
            objArti.setNombreArticulo(txtNombre.getText());
            objArti.setDescripcion(txDescripcion.getText());
            objArti.setIdProveedores(Integer.valueOf(txtIdProveedores.getText()));
            
            SubLineaProducto slp=new SubLineaProducto();
            slp.setIdSubLinea(Integer.valueOf(txtIdSubLinea.getText()));
            objArti.setSublineaProducto(slp);
            
            objArti.setLote(txtLote.getText());
            objArti.setCantidad(Integer.valueOf(txtCantidad.getText()));
            objArti.setIva(Double.valueOf(txtIva.getText()));
            objArti.setCosto(Double.valueOf(txtCosto.getText())); 
            objArti.setPrecioVenta(Double.valueOf(txtPrecioVenta.getText())); 
            utilidad=Double.valueOf(txtPrecioVenta.getText())-Double.valueOf(txtCosto.getText());
            objArti.setUtilidad(utilidad);
            objArti.setEstado(cbxEstado.getSelectedItem().toString());

        if(objCtrlArti.modificar(objArti)){
            JOptionPane.showMessageDialog(null,"Articulo Editado con Exito!");
            borrarJtable();
            ActualizarTablaEnArtiGui();
        }else{
            JOptionPane.showMessageDialog(null,"Error al Editar!!!");
        }
        
    }
    
    
    private void cbxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProveedorActionPerformed
        Proveedor prove=(Proveedor) cbxProveedor.getSelectedItem();
        String idProveedor = String.valueOf(prove.getIdProveedor());
        txtIdProveedores.setText(idProveedor);
    }//GEN-LAST:event_cbxProveedorActionPerformed

    private void cbxSubLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSubLineaActionPerformed
        SubLineaProducto slp=(SubLineaProducto)cbxSubLinea.getSelectedItem();
        String idSubLinea=String.valueOf(slp.getIdSubLinea());
        txtIdSubLinea.setText(idSubLinea);
    }//GEN-LAST:event_cbxSubLineaActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        int numCaracteres=80;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtNombre.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 80 caracteres");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDescripcionKeyTyped
         int numCaracteres=250;
        //System.out.print("-->"+letra_text.getText().length());
        if(txDescripcion.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 250 caracteres");
        }
    }//GEN-LAST:event_txDescripcionKeyTyped

    private void txtLoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoteKeyTyped
         int numCaracteres=50;
        //System.out.print("-->"+letra_text.getText().length());
        if(txtLote.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 50 caracteres");
        }
    }//GEN-LAST:event_txtLoteKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        int numCaracteres=11;
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo numeros!");
            txtCantidad.grabFocus();
        }
        
        if(txtCantidad.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 11 caracteres");
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtIvaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIvaKeyTyped
        int numCaracteres=3;
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo numeros!");
            txtIva.grabFocus();
        }
        
        if(txtIva.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 3 caracteres");
        }
        
    }//GEN-LAST:event_txtIvaKeyTyped

    private void txtCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyTyped
       int numCaracteres=8;
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo numeros!");
            txtCosto.grabFocus();
        }
        
        if(txtCosto.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 8 cifras");
        }
        
    }//GEN-LAST:event_txtCostoKeyTyped

    private void txtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyTyped
         int numCaracteres=8;
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo numeros!");
            txtPrecioVenta.grabFocus();
        }
        
        if(txtPrecioVenta.getText().length()>=numCaracteres){//en la primera digitada del caracter letra_text.getText().length() es cero
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se aceptan 8 cifras");
        }
        
//         double costo=0.0;
//        double precio=0.0;
//        double utilidad=0.0;
//        
//        costo=Double.parseDouble(txtCosto.getText());
//        utilidad=costo-precio;
//        txtUtilidad.setText(String.valueOf(utilidad));
        
        
    }//GEN-LAST:event_txtPrecioVentaKeyTyped

    private void cbxLineaArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLineaArticuloActionPerformed
       
        LineaProducto lp=(LineaProducto)cbxLineaArticulo.getSelectedItem();
        int idLinea=lp.getidLinea();
        objCtrlSubLi.cargarCBcondicionado(cbxSubLinea,idLinea); //COMBOBOX DE SUBLINEA ARTICULO  
        
    }//GEN-LAST:event_cbxLineaArticuloActionPerformed
    
     public void guardar(){
        
            Articulo objArti=new Articulo();
            double utilidad=0.0;        
            //DATOS DE ARTICULO
            objArti.setNombreArticulo(txtNombre.getText());
            objArti.setDescripcion(txDescripcion.getText());
            objArti.setIdProveedores(Integer.valueOf(txtIdProveedores.getText()));
            
            SubLineaProducto slp=new SubLineaProducto();
            slp.setIdSubLinea(Integer.valueOf(txtIdSubLinea.getText()));
            objArti.setSublineaProducto(slp);
            
            objArti.setLote(txtLote.getText());
            objArti.setCantidad(Integer.valueOf(txtCantidad.getText()));
            objArti.setIva(Double.valueOf(txtIva.getText()));
            objArti.setCosto(Double.valueOf(txtCosto.getText())); 
            objArti.setPrecioVenta(Double.valueOf(txtPrecioVenta.getText())); 
            utilidad=Double.valueOf(txtPrecioVenta.getText())-Double.valueOf(txtCosto.getText());
            objArti.setUtilidad(utilidad); 
            objArti.setEstado(cbxEstado.getSelectedItem().toString());
    
             if(objCtrlArti.guardar(objArti)){
                JOptionPane.showMessageDialog(null,"El Articulo se registro con Exito!");
                borrarJtable();
                ActualizarTablaEnArtiGui();
                limpiar();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null,"El Articulo NO Fue Registrado!");  
            }      
          }
        

    
    public void limpiar(){        
        txtNombre.setText("");     
        txtLote.setText("");
        txtCantidad.setText("");
        txtIva.setText("");
    } 
     
    public void ActualizarTablaEnArtiGui(){
        modelo=(DefaultTableModel)ArticulosGui.tblModuloArticulos.getModel();
        elqueOrdena=new TableRowSorter<TableModel>(modelo);
        ArticulosGui.tblModuloArticulos.setRowSorter(elqueOrdena);//con esto se puede ordenar por col el jtable de manera asc o desc
        CtrlArticulo objCtrlArti=new CtrlArticulo();
                
        ArrayList<Articulo> listado=new ArrayList();
        listado=objCtrlArti.traerTodosDos();
        Object []col=new Object[modelo.getColumnCount()];//creo un obj tipo Object del tamaño de las columnas de mi Table
                
       for(int index=0;index<listado.size();index++){//recorro el arrayList
            col[0]=listado.get(index).getCodigoArticulo();
            col[1]=listado.get(index).getNombreArticulo();
            col[2]=listado.get(index).getDescripcion();
            col[3]=listado.get(index).getNomProvee();
            col[4]=listado.get(index).getSublineaProducto().getDescLineaProd();
            col[5]=listado.get(index).getSublineaProducto().getSubLineaDescripcion();
            col[6]=listado.get(index).getLote();
            col[7]=listado.get(index).getCantidad();
            col[8]=listado.get(index).getIva();            
            col[9]=listado.get(index).getCosto();
            col[10]=listado.get(index).getPrecioVenta();
            col[11]=listado.get(index).getUtilidad();
            col[12]=listado.get(index).getEstado();
            modelo.addRow(col);//añado el object a la fila
       }
       ArticulosGui.tblModuloArticulos.setModel(modelo);
    }
    
     private void borrarJtable(){
        modelo=(DefaultTableModel)ArticulosGui.tblModuloArticulos.getModel();
        for (int i = ArticulosGui.tblModuloArticulos.getRowCount() -1; i >= 0; i--){ 
                modelo.removeRow(i); 
        }      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormClienteGui dialog = new FormClienteGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbxEstado;
    private javax.swing.JComboBox cbxLineaArticulo;
    private javax.swing.JComboBox cbxProveedor;
    private javax.swing.JComboBox cbxSubLinea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txDescripcion;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtIdProveedores;
    private javax.swing.JTextField txtIdSubLinea;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
