/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Control.CtrlProveedor;
import Modelo.Proveedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JEFERSSON
 */
public class ProveedorGui extends javax.swing.JInternalFrame {

    CtrlProveedor objCtrlProve=new CtrlProveedor();
    DefaultTableModel modelo;//modelo de datos
    TableRowSorter<TableModel> elqueOrdena;
    public static String ACCIONPROVE;
    public static int idProveedores;
    
    
    public ProveedorGui() {
        initComponents();
        btnEditarProvee.setEnabled(false);
//        btnEliminarProvee.setEnabled(false);
        EsconderColumnaCodigo();
        llenarJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscarProveedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        btnNuevoCliente = new javax.swing.JButton();
        btnEditarProvee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Gestion Proveedores");

        txtBuscarProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProveedorKeyReleased(evt);
            }
        });

        tblProveedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProveedor", "Nombre", "Numero Identidad", "Ciudad", "Direccion", "Telefono", "Email", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProveedores.setRowHeight(22);
        tblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedores);

        btnNuevoCliente.setBackground(new java.awt.Color(9, 46, 227));
        btnNuevoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setText("Nuevo Proveedor");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnEditarProvee.setBackground(new java.awt.Color(241, 100, 14));
        btnEditarProvee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditarProvee.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarProvee.setText("Editar");
        btnEditarProvee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProveeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnNuevoCliente)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProveedorKeyReleased
        String buscarC;
        buscarC=txtBuscarProveedor.getText();
        buscarEnTiempoReal(buscarC);
    }//GEN-LAST:event_txtBuscarProveedorKeyReleased

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
       ACCIONPROVE="Nuevo";
       FormProveedorGui objForProveGui=new FormProveedorGui(null, true);
       objForProveGui.setVisible(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnEditarProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProveeActionPerformed
        ACCIONPROVE="Editar";
        System.out.println(idProveedores);
        int filasele=0;
            filasele=tblProveedores.getSelectedRow();
            System.out.println("filasele="+filasele);
            idProveedores=Integer.valueOf(tblProveedores.getValueAt(filasele, 0).toString());
            System.out.println("idProoveedores= "+idProveedores);
        FormProveedorGui objFormProveGui=new FormProveedorGui(null, true);
        objFormProveGui.setVisible(true);
    }//GEN-LAST:event_btnEditarProveeActionPerformed

    private void tblProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedoresMouseClicked
            btnEditarProvee.setEnabled(true);
//            btnEliminarProvee.setEnabled(true);            
    }//GEN-LAST:event_tblProveedoresMouseClicked
    
    public void buscarEnTiempoReal(String texto){
        borrarJtable();//borro lo que hay en el JTABLE
        modelo=(DefaultTableModel)tblProveedores.getModel();
        elqueOrdena=new TableRowSorter<TableModel>(modelo);
        tblProveedores.setRowSorter(elqueOrdena);//con esto se puede ordenar por col el jtable de manera asc o desc
                        
        ArrayList<Proveedor> listado=new ArrayList();
        listado=objCtrlProve.BusquedaTiempoReal(texto);
        Object []col=new Object[modelo.getColumnCount()];//creo un obj tipo Object del tamaño de las columnas de mi Table
        for(int index=0;index<listado.size();index++){//recorro el arrayList
            col[0]=listado.get(index).getIdProveedor();
            col[1]=listado.get(index).getNombre();
            col[2]=listado.get(index).getNumeroIdentidad();
            col[3]=listado.get(index).getNomCiudad();
            col[4]=listado.get(index).getDireccion();            
            col[5]=listado.get(index).getTelefono();
            col[6]=listado.get(index).getEmail(); 
            col[7]=listado.get(index).getEstado();            
            modelo.addRow(col);
        } 
       
      tblProveedores.setModel(modelo);
         
     }
     
    private void borrarJtable(){
        for (int i = tblProveedores.getRowCount() -1; i >= 0; i--){ 
                modelo.removeRow(i); 
        }      
    }
//    
    /**
     * @param args the command line arguments
     */
    
    public void llenarJTable(){
        
        modelo=(DefaultTableModel)tblProveedores.getModel();                
        elqueOrdena=new TableRowSorter<TableModel>(modelo);
        tblProveedores.setRowSorter(elqueOrdena);//con esto se puede ordenar por col el jtable de manera asc o desc
        Proveedor objProve=new Proveedor();
        ArrayList<Proveedor> listado=new ArrayList<Proveedor>();
        listado=objCtrlProve.traerTodos();
        Object []col=new Object[modelo.getColumnCount()];//creo un obj tipo Object del tamaño de las columnas de mi Table
        
        for(int index=0;index<listado.size();index++){
            col[0]=listado.get(index).getIdProveedor();
            col[1]=listado.get(index).getNombre();
            col[2]=listado.get(index).getNumeroIdentidad();
            col[3]=listado.get(index).getNomCiudad();
            col[4]=listado.get(index).getDireccion();            
            col[5]=listado.get(index).getTelefono();
            col[6]=listado.get(index).getEmail();
            col[7]=listado.get(index).getEstado();
            modelo.addRow(col);
        }          
    }
    
    
     public void EsconderColumnaCodigo(){
        //metodo para esconder la columna que contiene el codigo de los contactos
        tblProveedores.getColumnModel().getColumn(0).setMaxWidth(0);
        tblProveedores.getColumnModel().getColumn(0).setMinWidth(0);
        tblProveedores.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblProveedores.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ClienteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ClienteGui dialog = new ClienteGui(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnEditarProvee;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblProveedores;
    private javax.swing.JTextField txtBuscarProveedor;
    // End of variables declaration//GEN-END:variables
}
