/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.CtrlResolucionFactura;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Modelo.ResolucionFactura;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Taky
 */
public class ResolucionFacturaGUI extends javax.swing.JDialog {

     DefaultTableModel modelo;//modelo de datos
     TableRowSorter<TableModel> elqueOrdena;
     
    public ResolucionFacturaGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        txtIdResolucion.setVisible(false);
        txtNroResolucion.setEnabled(false);
        jdcFecha.setEnabled(false);
        jdcFechaInicio.setEnabled(false);
        jdcFechaFin.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnEditar.setEnabled(false);
        consultarDatosTabla();
    }

    public void consultarDatosTabla() {
        modelo=(DefaultTableModel)tblResolucionFactura.getModel();//nos arroja el modelo es decir el jtable
        elqueOrdena=new TableRowSorter<TableModel>(modelo);//ordena por columnas descendiente o ascendente lo que hay en el jtable
        tblResolucionFactura.setRowSorter(elqueOrdena);//con esto se puede ordenar por col el jtable de manera asc o desc  
        
        CtrlResolucionFactura objCtrResoFac = new CtrlResolucionFactura();
        ArrayList<ResolucionFactura> listado = new ArrayList();
        listado = objCtrResoFac.listadoResolucionFactura();
        
        Object []col=new Object[modelo.getColumnCount()];//creo un obj tipo Object del tamaño de las columnas de mi Table

        for (int i = 0; i < listado.size(); i++) {
                col[0]=listado.get(i).getIdResolucionFactura();
                col[1]=listado.get(i).getNroResolucionFactura();
                col[2]=listado.get(i).getFecha();
                col[3]=listado.get(i).getFechaInicio();
                col[4]=listado.get(i).getFechaFin();
                modelo.addRow(col);//añado el object a la fila
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtNroResolucion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jdcFechaInicio = new com.toedter.calendar.JDateChooser();
        jdcFechaFin = new com.toedter.calendar.JDateChooser();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtIdResolucion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResolucionFactura = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fecha:");

        jLabel2.setText("Fecha Inicio:");

        jLabel3.setText("Fecha Fin:");

        jdcFecha.setDateFormatString("yyyy-MM-dd");

        jdcFechaInicio.setDateFormatString("yyyy-MM-dd");

        jdcFechaFin.setDateFormatString("yyyy-MM-dd");

        btnAgregar.setBackground(new java.awt.Color(25, 115, 14));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Guardar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(241, 100, 14));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(227, 9, 42));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(23, 165, 174));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Nueva");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nro Resolucion:");

        txtIdResolucion.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jdcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdcFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdcFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNroResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtIdResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIdResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jdcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jdcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("GESTION DE RESOLUCION FACTURA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tblResolucionFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdResolucion", "Nro Resolucion", "Fecha", "Fecha Inicio", "Fecha Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResolucionFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResolucionFacturaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblResolucionFactura);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       
        modificar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblResolucionFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResolucionFacturaMouseClicked
        
        int filasele = tblResolucionFactura.getSelectedRow();
        
        txtIdResolucion.setText(tblResolucionFactura.getValueAt(filasele, 0).toString());
        txtNroResolucion.setText(tblResolucionFactura.getValueAt(filasele, 1).toString());        
        String fecha1 = tblResolucionFactura.getValueAt(filasele, 2).toString();
        String fecha2 = tblResolucionFactura.getValueAt(filasele, 3).toString();
        String fecha3 = tblResolucionFactura.getValueAt(filasele, 4).toString();

        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        Date fechaTxt1;
        Date fechaTxt2;
        Date fechaTxt3;

        try {
            fechaTxt1 = formatoFecha.parse(fecha1);
            fechaTxt2 = formatoFecha.parse(fecha2);
            fechaTxt3 = formatoFecha.parse(fecha3);

            jdcFecha.setDate(fechaTxt1);
            jdcFechaInicio.setDate(fechaTxt2);
            jdcFechaFin.setDate(fechaTxt3);
            
            txtNroResolucion.setEnabled(true);
            jdcFecha.setEnabled(true);
            jdcFechaInicio.setEnabled(true);
            jdcFechaFin.setEnabled(true);
            btnAgregar.setEnabled(false);
            btnEliminar.setEnabled(true);
            btnEditar.setEnabled(true);

        } catch (ParseException ex) {
            Logger.getLogger(ResolucionFacturaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        //filas = filasele;
    }//GEN-LAST:event_tblResolucionFacturaMouseClicked
    
    private void borrarJtable(){// este metodo limpia todo el jtable
        for (int i = tblResolucionFactura.getRowCount() -1; i >= 0; i--){ 
                modelo.removeRow(i); 
        }      
    }
    
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       borrar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar();
        txtNroResolucion.setEnabled(true);
        jdcFecha.setEnabled(true);
        jdcFechaInicio.setEnabled(true);
        jdcFechaFin.setEnabled(true);
        btnAgregar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnEditar.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void agregar() {

        CtrlResolucionFactura objCtrResoFac = new CtrlResolucionFactura();
        ResolucionFactura objMdlResoFac = new ResolucionFactura();
        
        
        Date date1 = jdcFecha.getDate();
        Date date2 = jdcFechaInicio.getDate();
        Date date3 = jdcFechaFin.getDate();

        if (date1 == null || date2 == null || date3 == null) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {

            long d1 = date1.getTime();
            java.sql.Date fecha1 = new java.sql.Date(d1);

            long d2 = date2.getTime();
            java.sql.Date fecha2 = new java.sql.Date(d2);

            long d3 = date3.getTime();
            java.sql.Date fecha3 = new java.sql.Date(d3);
            
            objMdlResoFac.setNroResolucionFactura(Integer.valueOf(txtNroResolucion.getText()));            
            objMdlResoFac.setFecha(fecha1);
            objMdlResoFac.setFechaInicio(fecha2);
            objMdlResoFac.setFechaFin(fecha3);

            if (objCtrResoFac.agregar(objMdlResoFac)) {
                JOptionPane.showMessageDialog(null, "Sus datos fueron agregados exitosamente");
                borrarJtable();
                limpiar();
                consultarDatosTabla();
                txtNroResolucion.setEnabled(false);
                jdcFecha.setEnabled(false);
                jdcFechaInicio.setEnabled(false);
                jdcFechaFin.setEnabled(false);
                btnAgregar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnEditar.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(null, "Sus datos no fueron agregados");
            }
        }

    }
    
    public void limpiar(){
        txtIdResolucion.setText("");
        txtNroResolucion.setText("");
        jdcFecha.setDate(null);
        jdcFechaInicio.setDate(null);
        jdcFechaFin.setDate(null);
        
    }
    
    public void modificar() {
        int pkIdResolucion=0;
        CtrlResolucionFactura objCtrResoFac = new CtrlResolucionFactura();
        ResolucionFactura objMdlResoFac = new ResolucionFactura();
        int filasele = tblResolucionFactura.getSelectedRow();
        int idResolucion=Integer.valueOf(txtIdResolucion.getText());
       
        Date date1 = jdcFecha.getDate();
        Date date2 = jdcFechaInicio.getDate();
        Date date3 = jdcFechaFin.getDate();

        long d1 = date1.getTime();
        java.sql.Date fecha1 = new java.sql.Date(d1);

        long d2 = date2.getTime();
        java.sql.Date fecha2 = new java.sql.Date(d2);

        long d3 = date3.getTime();
        java.sql.Date fecha3 = new java.sql.Date(d3);
        
        objMdlResoFac.setIdResolucionFactura(idResolucion);
        objMdlResoFac.setNroResolucionFactura(Integer.valueOf(txtNroResolucion.getText()));
        objMdlResoFac.setFecha(fecha1);
        objMdlResoFac.setFechaInicio(fecha2);
        objMdlResoFac.setFechaFin(fecha3);

        if (objCtrResoFac.modificar(objMdlResoFac)) {
            JOptionPane.showMessageDialog(null, "Sus datos fueron modificados exitosamente");
            borrarJtable();
            consultarDatosTabla();
            limpiar();
            txtNroResolucion.setEnabled(false);
            jdcFecha.setEnabled(false);
            jdcFechaInicio.setEnabled(false);
            jdcFechaFin.setEnabled(false);
            btnAgregar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnEditar.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(null, "Sus datos no fueron modificados");
        }

    }

    public void borrar() {

        CtrlResolucionFactura objCtrResoFac = new CtrlResolucionFactura();
        if (objCtrResoFac.borrar(Integer.parseInt(txtIdResolucion.getText()))) {
            JOptionPane.showMessageDialog(null, "Sus datos fueron borrados exitosamente");
            borrarJtable();
            consultarDatosTabla();
            limpiar();
            txtNroResolucion.setEnabled(false);
            jdcFecha.setEnabled(false);
            jdcFechaInicio.setEnabled(false);
            jdcFechaFin.setEnabled(false);
            btnAgregar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnEditar.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(null, "Sus datos no fueron borrados");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResolucionFacturaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResolucionFacturaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResolucionFacturaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResolucionFacturaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResolucionFacturaGUI dialog = new ResolucionFacturaGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private com.toedter.calendar.JDateChooser jdcFechaFin;
    private com.toedter.calendar.JDateChooser jdcFechaInicio;
    private javax.swing.JTable tblResolucionFactura;
    private javax.swing.JTextField txtIdResolucion;
    private javax.swing.JTextField txtNroResolucion;
    // End of variables declaration//GEN-END:variables
}
