package Vista;


import Control.CtrlTipoDocumento;
import Modelo.TipoDocumento;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JEFERSSON
 */
public final class TipoDocumentoGui extends javax.swing.JDialog {
 
  //VARIABLES GLOBALES EN TODA ESTA CLASE  
  CtrlTipoDocumento objCtrlTD=new CtrlTipoDocumento();
  DefaultTableModel modelo;//modelo de datos
  TableRowSorter<TableModel> elqueOrdena;
  
    public TipoDocumentoGui(java.awt.Frame parent, boolean modal) {// constructor de la GUI
        super(parent, modal);
        initComponents();
        txtIdTipoDocumento.setVisible(false);//esconde el campo del idBarrio ya que el usuario no tiene porque ver el id
        txtDescripcion.setEnabled(false);
        btnGuardar.setEnabled(false);//desactiva el boton
        btnEliminar.setEnabled(false);//desactiva el boton
        btnEditar.setEnabled(false);//desactiva el boton
        setLocationRelativeTo(null);//centra la ventana
        EsconderColumnaCodigo();//llamado de metodo, que esconde la columna de la tabla que contiene todos los idBarrio 
        traerDatosTable();//al darle run a esta ventana se carga todos los datos desde la BD en la tabla
        //al ser este metodo lo primero que se carga cuando le damos run a la ventana, es aqui donde ponemos todo lo que 
        //queramos que se ejecute en primera medida.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipoDocumento = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        txtIdTipoDocumento = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TIPO DOCUMENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setText("Descripcion:");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(25, 115, 14));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(241, 100, 14));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        tblTipoDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTipoDocumentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTipoDocumento);

        btnEliminar.setBackground(new java.awt.Color(227, 9, 42));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtIdTipoDocumento.setEditable(false);

        jButton1.setBackground(new java.awt.Color(23, 165, 174));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtIdTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(txtIdTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      guardar();//llamamos al metodo guardar() que mas abajo esta todo lo que contiene
    }//GEN-LAST:event_btnGuardarActionPerformed
    
      public void guardar(){// metodo que ejecuta algo en este caso instrucciones para insertar en la base de datos      
        TipoDocumento objTD=new TipoDocumento();//creamos el objeto a partir de la clase Barrio
        objTD.setDescripcion(txtDescripcion.getText());//seteamos la variable Nombre con lo que contenga el textfield llamado txtNombre
        //seteamos la variable Comuna con lo que contenga el textfield llamado txtComuna
        
        if(objCtrlTD.guardar(objTD)){// como el metodo guardar nos arroja true o false lo metemos en esta condicion
            //si todo salio bien al momento de insertar nos arroja true y entra a las siguientes acciones
            JOptionPane.showMessageDialog(null,"El tipo de identidad se registro!");//mensaje
            borrarJtable();//Hacemos un llamado al metodo borrarJtable(); esto con el fin de hacer el efecto de actualizar el table
            traerDatosTable();//hacemos el llamado del metodo traerDatos que nos traer todo la lista de barrios de la BD
            //como arriba borramos todo lo que habia en el table con esto volvemos a traer datos dando el efecto de actualizar
            limpiar();//hacemos el llamado del metodo limpiar que lo que hace es limpiar los campos idBarrio(escondido),nombre,comuna
            btnGuardar.setEnabled(false);//si existe algo en el jtextfield activa el boton guardar
            btnEliminar.setEnabled(false);
            btnEditar.setEnabled(false);  
        }else{
           JOptionPane.showMessageDialog(null,"El tipo de identidad NO Fue Registrado!");  
         }      
    }
    
    //este metodo es propio del JTable es decir usamos el evento MouseClicked que no es mas que cada vez que hacemos click en 
    //una fila sucede algo y ese algo es lo que hay dentro de este metodo  
    private void tblTipoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTipoDocumentoMouseClicked
            int filasele=0;//variable entera que contendra el numero de la variable donde dimos click
            filasele=tblTipoDocumento.getSelectedRow();//nos arroja el numero da fila seleccionada que empieza de 0 a n filas
            System.out.println("filasele="+filasele);//aqui se dan cuenta en consola que numero de fila es la clickeada
            //SETEAMOS todos los jtextfield de idBarrrio,txtNombre,txtComuna
            //el metodo getValueAt lo que hace es seleccionar de x fila y x columna lo que se almacena ahi, es como una coordenada
            /*
                        columna 0 columna 1
             fila 0--> | Salomia |     4   |
             fila 1--> | Popular |     4   |
            
            */
            txtIdTipoDocumento.setText(tblTipoDocumento.getValueAt(filasele, 0).toString());
            txtDescripcion.setText(tblTipoDocumento.getValueAt(filasele, 1).toString());
            
            txtDescripcion.setEnabled(true);
            btnGuardar.setEnabled(false);//desactive el boton guardar
            btnEliminar.setEnabled(true);//activa el boton
            btnEditar.setEnabled(true);//activa el boton
            
    }//GEN-LAST:event_tblTipoDocumentoMouseClicked

  
     
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       editar();//hacemos llamado del metodo editar() mas abajo esta!
    }//GEN-LAST:event_btnEditarActionPerformed
    
       public void editar(){// metodo editar que hace unas instrucciones para editar un registro
        TipoDocumento objTD;// referenciamos el objeto Barrio
        int idtipoidentidad=Integer.valueOf(txtIdTipoDocumento.getText());//almacenamos en esta variable lo que hay en el txtfield oculto que tiene el idBario
        String descripcion=txtDescripcion.getText();//almacenamos en esta variable lo que hay en el txtfield nombre
        //almacenamos en esta variable lo que hay en el txtfield comuna
        
        objTD=new TipoDocumento(idtipoidentidad, descripcion);//instanciamos el objeto y le pasamos los valores de las variables que esta arriba
        
        if(objCtrlTD.modificar(objTD)){// validamos que se cumpla todo la modificacion recordemos que el metodo modificar arroja true o false
            JOptionPane.showMessageDialog(null,"El tipo de Documento se Edito con Exito!");
            //actualizamos el table
            borrarJtable();
            traerDatosTable();
            //limpiamos los campos textfield
            limpiar();
            txtDescripcion.setEnabled(false);
            btnGuardar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnEditar.setEnabled(false);  
        }else{
            JOptionPane.showMessageDialog(null,"El tipo de Documento No se Edito!");
        }   
        
    }
       
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       eliminar();//hacemos el llamado de el metodo ellimiar, abajo esta!
    }//GEN-LAST:event_btnEliminarActionPerformed
    public void eliminar(){
        int idtipoidentidad=Integer.valueOf(txtIdTipoDocumento.getText());//almacenamos en esta variable lo que hay en el txtfield oculto que tiene el idBario
        int rspta=JOptionPane.showConfirmDialog(null, "¿Esta seguro de Eliminar este tipo de Documento?",
                "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);//preguntamos si realmente quiere eliminar el barrio
        //esa respuesta la almacenamos en una variable entero puesto que este metodo nos arroja 0 si clickeamos Aceptar
        // y 1 si clickeamos Cancelar
        if(rspta==0){//comparamos la rspta, si se cumple hace lo siguiente
            if(objCtrlTD.eliminar(idtipoidentidad)){//recordemos que el metodo eliminar()arroja true o false si todo salio bien o mal
                JOptionPane.showMessageDialog(null,"Se elimino el tipo de documento!");
                //actualizamos el jtable
                borrarJtable();
                traerDatosTable();
                //limpiamos los jtextfield
                limpiar();
                txtDescripcion.setEnabled(false);
                btnGuardar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnEditar.setEnabled(false); 
                
            }
        }
    }
    
    
    //METODO QUE TIENE EL EVENTO QUE SE EJECUTA CUANDO DIGITAMOS ALGO Y POR CADA TECLA UNDIDA HACE ALGO
    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
        String nombreSinEspacios=txtDescripcion.getText().trim();//quita todos los espacios en blanco de una cadena es decir: Ejemplo
        String idTipoDocumento=txtIdTipoDocumento.getText();
        // "    miguel" arrojaria "miguel"
        //una vez limpia nuestro campo de espacios en blanco
        if(nombreSinEspacios.length()>0 && idTipoDocumento.length()==0){//comparamos que sea mayor a 0 es decir que tenga algo letras o numeros que exista algo
            btnGuardar.setEnabled(true);            
        }else{
            btnGuardar.setEnabled(false); //si no pues lo oculta
        }
    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar();
        txtDescripcion.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnEditar.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void limpiar(){//metodo que limpia los jtextfield
        //como vemos no tiene ciencia, es solo setear lo campos y ponerlos en blanco con "", y listo
        txtIdTipoDocumento.setText("");
        txtDescripcion.setText("");
        
    }
    
    private void borrarJtable(){// este metodo limpia todo el jtable
        for (int i = tblTipoDocumento.getRowCount() -1; i >= 0; i--){ 
                modelo.removeRow(i); 
        }      
    }
    
    public void traerDatosTable(){//como su nombre lo indica va a traer todos los datos en el jtable desde la base de datos
        modelo=(DefaultTableModel)tblTipoDocumento.getModel();//nos arroja el modelo es decir el jtable
        elqueOrdena=new TableRowSorter<TableModel>(modelo);//ordena por columnas descendiente o ascendente lo que hay en el jtable
        tblTipoDocumento.setRowSorter(elqueOrdena);//con esto se puede ordenar por col el jtable de manera asc o desc
                       
        ArrayList<TipoDocumento> listado=new ArrayList();//declaramos e instanciamos un array list de tipo Barrio llamado listado
        listado=objCtrlTD.traer();//almacenamos en listado lo que arroja el metodo listadoBarrio() que esta en la clase CtrlBarrio
        //recordemos que ese metodo lo que arroja es un arraylist(arrayList es como un vector mejorado mil veces) INVESTIGUEN MEJOR!
        Object []col=new Object[modelo.getColumnCount()];//creo un obj tipo Object del tamaño de las columnas de mi Table
               
       for(int index=0;index<listado.size();index++){//recorro el arrayList
                col[0]=listado.get(index).getCodigoDocumento();
                col[1]=listado.get(index).getDescripcion();
                                       
                modelo.addRow(col);//añado el object a la fila
       }
     
    }
    
    public void EsconderColumnaCodigo(){
        //metodo para esconder la columna que contiene el codigo de los Barios
        tblTipoDocumento.getColumnModel().getColumn(0).setMaxWidth(0);
        tblTipoDocumento.getColumnModel().getColumn(0).setMinWidth(0);
        tblTipoDocumento.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblTipoDocumento.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoDocumentoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoDocumentoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoDocumentoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoDocumentoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TipoDocumentoGui dialog = new TipoDocumentoGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblTipoDocumento;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdTipoDocumento;
    // End of variables declaration//GEN-END:variables
}
